### ISSUE TITLE
Once we purchased the paid version - we can no longer install this. PLEASE HELP!

### ISSUE THREAD

**Issue by rbefraim** [creativetimofficial/ct-argon-dashboard-pro-nodejs#1]
Dear Creative Tim Team:

We're out of our wits and been spending too long trying to solve an issue which happened ever since we installed the paid version of Argon.   We just want to install this on Heroku so we can customize the dashboard for a demo we're working on.

We're having the following bug:  The code 'appears' to work fine locally but only when we deploy to Heroku. In Heroku, I am able to register users but once registered can't log in. As I click login, it keeps on loading and opens the same page. I figured out the problem is with passport.js(authentication middleware for Node.js.).You can see code on
Github:https://github.com/rbefraim/digibiosys
Heroku credentials:login: ronen@digibiosys.com / password: DN7eM.d-rnUE}93a 

Please let us know how we can solve this..... Very grateful as time is of the essence and we really don't know what to do... thanks

**Comment by supportudevoffice** [comment]
Hello,
We have tried logging into Heroku using the provided credentials and they seem to be invalid. 
We also suspect that you did not start the docker containers in order to have Redis save your sessions or did not run the migrations and seeds. Please make sure that you run `docker-compose up -d` in the project directory and also `npm run knex migrate:latest` and `npm run knex seed:run` 

If the above seem to have no effect, please email us some working Heroku credentials at support@udevoffice.com

**Comment by rbefraim** [comment]
Thank you guys.

The corrected credentials for heroku are

user: ronen@digibiosys.com
Password: Digilove100


Thanks!

**Comment by supportudevoffice** [comment]
It appears that you are using the wrong credentials for the REDIS and POSTGRES services.
In your env files you are using credentials that are different than the ones in Heroku. 

In Heroku, for REDIS you have the following credentials:  
Password: p33d44b4ea76f6d5bd2a39425c518648b5abf84fb39c15bc18cf9************
User: h
In your env files you have the following:
Password: 4677c6e196673d287db3b22f4cb1e170409f3403c7d7763c4130************
User: gyoqclnceuuxff

**Comment by supportudevoffice** [comment]
From what we can see, the credentials used in the ENV files and the ones from your Heroku services do not match. 
Please check both PostgreSQL and Redis connection credentials in your .env files so that they match the ones of the services that you use.

**Comment by rbefraim** [comment]
+chandrika@digibiosys.com <chandrika@digibiosys.com> Chandrika please
respond thanks

**Comment by supportudevoffice** [comment]
Hello there,
Can you please confirm that this issue has been resolved in order to close it?
Thank you!

**Comment by rbefraim** [comment]
Thank you. The issue has not been resolved. I had to hire an external
developer to fix the bugs in your program. If you can't reimburse me - can
you at least please provide a partial refund (and that is assuming I can
make it work...?). thanks, R
